import { useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import { PageContainer } from '../../components/layout/PageContainer';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Badge } from '../../components/ui/Badge';
import { PhaseIndicator } from '../../components/game/PhaseIndicator';
import { EvidenceMatrixHeatmap } from '../../components/visualizations/EvidenceMatrixHeatmap';
import { useGameStore, useAnalysisStore } from '../../stores';
import { pageVariants, cardVariants } from '../../utils';

export function ReportPage() {
  const { scenarioId } = useParams<{ scenarioId: string }>();
  const navigate = useNavigate();
  const { scenarioConfig, selectedParadigms, activeParadigm, setPhase } = useGameStore();
  const { currentAnalysis } = useAnalysisStore();

  useEffect(() => {
    setPhase('report');
  }, [setPhase]);

  // Get report content - backend uses 'report' field, but check 'full_report' as fallback
  const reportContent = currentAnalysis?.report || currentAnalysis?.full_report || generateFallbackReport();

  function generateFallbackReport() {
    if (!scenarioConfig) return '';

    return `# BFIH Analysis Report

## Executive Summary

This analysis examined the proposition: "${scenarioConfig.proposition || scenarioConfig.narrative}"

### Paradigms Analyzed
${scenarioConfig.paradigms?.map((p) => `- **${p.id}**: ${p.name}`).join('\n') || 'No paradigms'}

### Hypotheses Evaluated
${scenarioConfig.hypotheses?.map((h) => `- **${h.id}**: ${h.name}`).join('\n') || 'No hypotheses'}

---

## Methodology

The BFIH (Bayesian Framework for Intellectual Honesty) methodology was applied with the following forcing functions:

1. **Ontological Scan**: Verified coverage across 7 epistemic domains
2. **Ancestral Check**: Examined historical precedents and solutions
3. **Paradigm Inversion**: Generated inverse hypotheses for each paradigm
4. **MECE Synthesis**: Ensured hypotheses are mutually exclusive and collectively exhaustive

---

## Evidence Summary

${scenarioConfig.evidence_clusters?.length || 0} evidence clusters were analyzed.

${scenarioConfig.evidence_clusters?.map((c) => `
### ${c.cluster_name}

${c.items?.map((item) => `- ${item.content}`).join('\n') || 'No items'}
`).join('\n') || 'No evidence clusters available.'}

---

## Conclusions

The Bayesian analysis reveals how different epistemic paradigms lead to different posterior probabilities for each hypothesis. This demonstrates the fundamental insight of the BFIH framework: our conclusions are necessarily influenced by our prior assumptions and worldview.

---

*Report generated by the BFIH Hypothesis Tournament*
`;
  }

  if (!scenarioConfig) {
    return (
      <PageContainer className="flex items-center justify-center min-h-[60vh]">
        <Card className="p-8 text-center">
          <p className="text-text-secondary mb-4">No scenario loaded</p>
          <Button onClick={() => navigate('/')}>Go Home</Button>
        </Card>
      </PageContainer>
    );
  }

  const paradigms = scenarioConfig.paradigms?.filter(
    (p) => selectedParadigms.includes(p.id)
  ) || [];

  // Get evidence clusters from analysis metadata (where they actually live)
  // Fall back to scenarioConfig for backwards compatibility
  const evidenceClusters = currentAnalysis?.metadata?.evidence_clusters
    || scenarioConfig.evidence_clusters
    || [];

  return (
    <motion.div
      variants={pageVariants}
      initial="initial"
      animate="animate"
      exit="exit"
    >
      <PageContainer>
        {/* Phase Indicator */}
        <PhaseIndicator currentPhase="report" className="mb-8" />

        {/* Title */}
        <motion.div variants={cardVariants} className="text-center mb-8">
          <h1 className="text-3xl font-bold text-text-primary mb-2">
            BFIH Analysis Report
          </h1>
          <p className="text-lg text-text-secondary">
            Complete methodology and findings
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-4 gap-6">
          {/* Sidebar - Table of Contents */}
          <div className="lg:col-span-1">
            <motion.div variants={cardVariants} className="sticky top-24">
              <Card className="p-4">
                <h3 className="text-sm font-medium text-text-muted uppercase tracking-wide mb-3">
                  Contents
                </h3>
                <nav className="space-y-2">
                  {[
                    'Executive Summary',
                    'Methodology',
                    'Paradigms',
                    'Hypotheses',
                    'Evidence',
                    'Posteriors',
                    'Conclusions',
                  ].map((section) => (
                    <a
                      key={section}
                      href={`#${section.toLowerCase().replace(' ', '-')}`}
                      className="block text-sm text-text-secondary hover:text-accent transition-colors"
                    >
                      {section}
                    </a>
                  ))}
                </nav>
              </Card>

              {/* Quick Stats */}
              <Card className="p-4 mt-4">
                <h3 className="text-sm font-medium text-text-muted uppercase tracking-wide mb-3">
                  Analysis Stats
                </h3>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-text-secondary">Paradigms</span>
                    <Badge variant="secondary">
                      {scenarioConfig.paradigms?.length || 0}
                    </Badge>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-text-secondary">Hypotheses</span>
                    <Badge variant="secondary">
                      {scenarioConfig.hypotheses?.length || 0}
                    </Badge>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-text-secondary">Evidence</span>
                    <Badge variant="secondary">
                      {currentAnalysis?.metadata?.evidence_items_count
                        || evidenceClusters.reduce(
                          (sum, c) => sum + (c.items?.length || c.evidence_ids?.length || 0),
                          0
                        )
                        || 0}
                    </Badge>
                  </div>
                </div>
              </Card>

              {/* Actions */}
              <div className="mt-4 space-y-2">
                <Button
                  variant="secondary"
                  className="w-full"
                  onClick={() => {
                    const blob = new Blob([reportContent], { type: 'text/markdown' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `bfih-report-${scenarioId}.md`;
                    a.click();
                    URL.revokeObjectURL(url);
                  }}
                >
                  Download Report
                </Button>
                <Button
                  variant="ghost"
                  className="w-full"
                  onClick={() => navigator.clipboard.writeText(reportContent)}
                >
                  Copy to Clipboard
                </Button>
              </div>
            </motion.div>
          </div>

          {/* Main Report Content */}
          <div className="lg:col-span-3">
            <motion.div variants={cardVariants}>
              <Card className="p-8">
                <article className="prose prose-invert prose-lg max-w-none
                  prose-headings:text-text-primary
                  prose-p:text-text-secondary
                  prose-strong:text-text-primary
                  prose-li:text-text-secondary
                  prose-a:text-accent hover:prose-a:underline
                  prose-code:text-accent prose-code:bg-surface-2 prose-code:px-1 prose-code:rounded
                  prose-hr:border-border
                ">
                  <ReactMarkdown>{reportContent}</ReactMarkdown>
                </article>
              </Card>
            </motion.div>

            {/* Evidence Matrix */}
            <motion.div variants={cardVariants} className="mt-6">
              <EvidenceMatrixHeatmap
                hypotheses={scenarioConfig.hypotheses || []}
                clusters={evidenceClusters}
                paradigms={paradigms}
                activeParadigm={activeParadigm}
              />
            </motion.div>
          </div>
        </div>

        {/* Navigation */}
        <motion.div
          variants={cardVariants}
          className="flex justify-between items-center mt-8"
        >
          <Button
            variant="ghost"
            onClick={() => navigate(`/game/${scenarioId}/resolution`)}
          >
            Back to Resolution
          </Button>
          <Button
            size="lg"
            onClick={() => navigate(`/game/${scenarioId}/debrief`)}
          >
            Continue to Debrief
          </Button>
        </motion.div>
      </PageContainer>
    </motion.div>
  );
}
